[theme]
base = "dark"
primaryColor = "#00F2FE"
backgroundColor = "#070A13"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"

[server]
headless = true
port = 8585
enableCORS = false
enableXsrfProtection = false
